// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsDkRB2A6-IPJs1n-5siCVWiMOETudKXo',
    appId: '1:60336439697:android:5863a0a5ba25821dbc1a30',
    messagingSenderId: '60336439697',
    projectId: 'smarthcane-11b47',
    databaseURL: 'https://smarthcane-11b47-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthcane-11b47.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSvhNl3lT7kFDEzx30kM5srxcgxCB5VXM',
    appId: '1:60336439697:ios:8ae34e93cb37e07fbc1a30',
    messagingSenderId: '60336439697',
    projectId: 'smarthcane-11b47',
    databaseURL: 'https://smarthcane-11b47-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthcane-11b47.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSvhNl3lT7kFDEzx30kM5srxcgxCB5VXM',
    appId: '1:60336439697:ios:8ae34e93cb37e07fbc1a30',
    messagingSenderId: '60336439697',
    projectId: 'smarthcane-11b47',
    databaseURL: 'https://smarthcane-11b47-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthcane-11b47.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkyPOmWN_fPtcKL_tuKM-w9OIQxDgTeH4',
    appId: '1:60336439697:web:672d74a2ccc1e22abc1a30',
    messagingSenderId: '60336439697',
    projectId: 'smarthcane-11b47',
    authDomain: 'smarthcane-11b47.firebaseapp.com',
    databaseURL: 'https://smarthcane-11b47-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthcane-11b47.firebasestorage.app',
    measurementId: 'G-K3JMDK5CST',
  );
}
